FROM ubuntu:18.04
RUN apt-get update && apt-get upgrade -y \
  && apt-get install curl -y \
  && rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

CMD /root/.cargo/bin/rustc --version
